"""
Utility Helpers
Export functions, text formatting, and report metrics.
"""

import re
import json
import math
import datetime
from pathlib import Path
from typing import Optional
from utils.logger import get_logger

logger = get_logger(__name__)


# ── Text Metrics ────────────────────────────────────────────────────────────

def word_count(text: str) -> int:
    """Count words in text."""
    return len(text.split())


def reading_time_minutes(text: str, wpm: int = 238) -> int:
    """Estimate reading time in minutes (avg 238 wpm for adults)."""
    return max(1, math.ceil(word_count(text) / wpm))


def char_count(text: str) -> int:
    """Count characters (excluding spaces)."""
    return len(text.replace(" ", ""))


def sentence_count(text: str) -> int:
    """Count sentences approximately."""
    return len(re.findall(r'[.!?]+', text))


def get_report_metrics(text: str) -> dict:
    """Return a comprehensive metrics dict for a report."""
    words = word_count(text)
    return {
        "words": words,
        "characters": char_count(text),
        "sentences": sentence_count(text),
        "paragraphs": len([p for p in text.split("\n\n") if p.strip()]),
        "reading_time": reading_time_minutes(text),
    }


# ── Export Functions ─────────────────────────────────────────────────────────

def export_markdown(topic: str, result: str, agent_outputs: list[dict]) -> bytes:
    """Export report as a well-formatted Markdown document."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# {topic}",
        f"> Generated by NEXUS Multi-Agent Intelligence Platform",
        f"> **Date:** {now}",
        "",
        "---",
        "",
        "## Executive Report",
        "",
        result,
        "",
        "---",
        "",
        "## Agent Pipeline Outputs",
        "",
    ]
    for agent in agent_outputs:
        lines.append(f"### {agent.get('icon', '🤖')} {agent.get('name', 'Agent')}")
        lines.append("")
        lines.append(agent.get("output", ""))
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*This report was autonomously generated using a multi-agent AI pipeline.*")
    return "\n".join(lines).encode("utf-8")


def export_json(topic: str, result: str, agent_outputs: list[dict]) -> bytes:
    """Export full report data as JSON."""
    payload = {
        "meta": {
            "platform": "NEXUS Multi-Agent Intelligence Platform",
            "version": "2.0.0",
            "generated_at": datetime.datetime.now().isoformat(),
            "topic": topic,
        },
        "metrics": get_report_metrics(result),
        "final_report": result,
        "agent_pipeline": [
            {
                "agent": a.get("name"),
                "role": a.get("role"),
                "output": a.get("output"),
            }
            for a in agent_outputs
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False).encode("utf-8")


def export_txt(topic: str, result: str) -> bytes:
    """Export plain text report."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = (
        f"NEXUS MULTI-AGENT INTELLIGENCE PLATFORM\n"
        f"{'='*50}\n"
        f"Topic: {topic}\n"
        f"Generated: {now}\n"
        f"{'='*50}\n\n"
        f"{result}\n\n"
        f"{'='*50}\n"
        f"Generated by NEXUS · nexus.ai\n"
    )
    return content.encode("utf-8")


# ── Text Formatting ──────────────────────────────────────────────────────────

def truncate(text: str, max_chars: int = 200) -> str:
    """Truncate text to max_chars with ellipsis."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip() + "…"


def sanitize_filename(name: str) -> str:
    """Convert a string to a safe filename."""
    return re.sub(r"[^\w\-_. ]", "_", name)[:60].strip()


def format_elapsed(seconds: float) -> str:
    """Format elapsed seconds to human-readable string."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    m, s = divmod(int(seconds), 60)
    return f"{m}m {s}s"
